# Generated by Django 3.1.4 on 2020-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twilio_account_sid',
            field=models.CharField(error_messages={'unique': 'A user with that Twilio account SID already exists.'}, max_length=100, null=True, unique=True, verbose_name='Twilio account SID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='balance'),
        ),
    ]
