# Generated by Django 3.1.4 on 2020-12-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='alias/pseudonym'),
        ),
    ]
