# Generated by Django 3.1.4 on 2020-12-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201213_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twilio_account_sid',
        ),
    ]
