# Generated by Django 3.1.4 on 2020-12-16 23:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_twilio_account_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_tickets_ttl',
            field=models.JSONField(default=accounts.models.generate_initial_extra_tickets_ttl, verbose_name='extra tickets TTL'),
        ),
    ]
