# Generated by Django 3.1.4 on 2021-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emaillistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_digit',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='RUT check digit'),
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
