# Generated by Django 3.1.4 on 2021-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_rut'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='accounts_us_telegra_de466c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rut'], name='accounts_us_rut_a2654b_idx'),
        ),
    ]
