# Generated by Django 3.1.4 on 2020-12-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_extra_tickets_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='winnings',
            field=models.PositiveIntegerField(default=0, verbose_name='winnings'),
        ),
    ]
