# Generated by Django 3.1.4 on 2020-12-17 00:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_winnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='extra_tickets_ttl',
            field=models.JSONField(blank=True, default=accounts.models.generate_initial_extra_tickets_ttl, verbose_name='extra tickets TTL'),
        ),
    ]
