[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = [
    "Alex Apt Iberkleid <aapt@uc.cl>",
    "Ariel Martínez Silberstein <amartinez5@uc.cl>",
]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.4"
djangorestframework = "^3.12.2"
gunicorn = "^20.0.4"
dj_database_url = "^0.5.0"
sentry_sdk = "^0.19.4"
django-cors-headers = "^3.5.0"
psycopg2-binary = "^2.8.6"
whitenoise = "^5.2.0"
requests = "^2.25.0"
apscheduler = "^3.6.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"

[tool.black]
line-length = 120
target-version = ["py36", "py37", "py38"]
exclude = '/(\.venv)/'

[build-system]
requires = ["poetry>=1.0.3"]
build-backend = "poetry.masonry.api"


