# Generated by Django 3.1.4 on 2021-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Scheduled'), (3, 'Sent')], default=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
