# Generated by Django 3.1.4 on 2021-03-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210213_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['scheduled_for']},
        ),
    ]
