# Generated by Django 3.1.4 on 2020-12-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'ordering': ('-created_at',)},
        ),
    ]
