# Generated by Django 3.1.4 on 2021-03-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='movement number'),
        ),
    ]
