name: staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Heroku Container Registry
        run: heroku container:login

      # https://stackoverflow.com/questions/59537030/release-phase-with-container-registry-on-heroku-runs-container.
      - name: Build and push
        run: heroku container:push --app ${{ secrets.HEROKU_STAGING_NAME }} web release --recursive --arg DJANGO_ENV=production,DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}

      - name: Release the image
        run: heroku container:release --app ${{ secrets.HEROKU_STAGING_NAME }} release web
